services:
  hdsphere-base:
    build: 
      context: ./hadoop-base
      dockerfile: Dockerfile
    image: hdsphere-base

  hdsphere-master:
    build: 
      context: ./master
      dockerfile: Dockerfile
    image: hdsphere-master
    depends_on:
      - hdsphere-base
    
  hdsphere-slave:
    build: 
      context: ./slave
      dockerfile: Dockerfile
    image: hdsphere-slave
    depends_on:
      - hdsphere-base
    