networks:
  hadoop-net:
    driver: bridge
services:
  master:
    image: master-official
    container_name: master
    hostname: minhquang-master
    volumes:
      - hdfs_namenode:/home/hadoopminhquang/hadoop/hadoop_data/hdfs/namenode
      - ./scripts:/home/hadoopminhquang/scripts


    ports:
      - "60070:50070"
      - "9004:9004"
      - "9870:9870"
      - "9864:9864"
      - "8042:8042"
      - "8088:8088"
    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
volumes:
  hdfs_namenode:
