networks:
  hadoop-net:
    driver: bridge
services:
  hdsphere-master:
    image: hdsphere-pig
    container_name: hdsphere-master
    hostname: quochuy026-master

    ports:
      - "60070:50070"
      - "9004:9004"
      - "9870:9870"
      - "9864:9864"
      - "8042:8042"
      - "8088:8088"
    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
  hdsphere-slave1:
    image: hdsphere-slave
    container_name: hdsphere-slave1
    hostname: quochuy026-slave1
    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

  hdsphere-slave2:
    image: hdsphere-slave
    container_name: hdsphere-slave2
    hostname: quochuy026-slave2
    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

