services:
  master:
    image: hadoop-master1
    container_name: master
    hostname: minhquang-master

    ports:
      - "60070:50070"
      - "9004:9004"
      - "9870:9870"
      - "9864:9864"
      - "8042:8042"
      - "8088:8088"
    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

  slave1:
    image: hadoop-slave1
    container_name: slave1
    hostname: minhquang-slave1

    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

  slave2:
    image: hadoop-slave1
    container_name: slave2
    hostname: minhquang-slave2

    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

networks:
  hadoop-net:
    driver: bridge

